{% set version = "1.3.5" %}

package:
  name: nomino
  version: {{ version }}

source:
  url: https://github.com/yaa110/nomino/archive/{{ version }}.tar.gz
  sha256: 35df10b30608c6ce733fe57625247621f8b2c51d99dc68421114b54880424ed2

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - nomino --help

about:
  home: https://github.com/yaa110/nomino
  dev_url: https://github.com/yaa110/nomino
  license: MIT
  license_family: MIT
  license_file: LICENSE-MIT
  summary: Batch rename utility for developers 

extra:
  recipe-maintainers:
    - apcamargo
